# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkOrderApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WorkOrderApp
  pod 'Alamofire'
  pod 'IQKeyboardManager'
  pod 'SwiftyJSON'
  pod 'Toast-Swift'
  pod 'PKHUD'
  pod 'SDWebImage'
end
